# Generated by Django 3.2 on 2021-05-01 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Emplyee_Name', models.CharField(max_length=20)),
                ('Email_Id', models.CharField(max_length=20)),
                ('Contact_No', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Person_Info',
            fields=[
                ('Missing_Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Image', models.CharField(max_length=1000)),
                ('Age', models.IntegerField()),
                ('Email_Id', models.CharField(max_length=20)),
                ('Contact_No', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('Date_Missing', models.DateField()),
                ('Date_Found', models.DateField()),
                ('Status', models.BooleanField()),
                ('Employee_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.employee')),
            ],
            options={
                'db_table': 'Person_Info',
            },
        ),
    ]
