# Generated by Django 3.2 on 2021-05-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_info',
            name='Image',
            field=models.ImageField(upload_to=''),
        ),
    ]
