# Generated by Django 3.2 on 2021-05-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_person_info_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_info',
            name='Date_Found',
            field=models.DateField(default='NULL'),
        ),
    ]
